
spring:
  datasource:
    url: jdbc:h2:mem:crypto-db
    driver-class-name: org.h2.Driver
    username: trader
    password: trader_pw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
